name: Job Scraper à 12h (France)

on:
  schedule:
    # 10h UTC = 12h en été (UTC+2)
    - cron: '0 10 * * *'
    # 11h UTC = 12h en hiver (UTC+1)
    - cron: '0 11 * * *'
  workflow_dispatch:  # Pour lancer manuellement

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python      
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python job_scraper.py
